// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebyzfwrteyxpfrgibkag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVieXpmd3J0ZXl4cGZyZ2lia2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NjM4ODUsImV4cCI6MjA1ODIzOTg4NX0.cZUDa5WTe-xN7sgY6lpquqVPM24BxooCnPdbr_EV4qQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);